import { NextResponse } from 'next/server';
import { lessonDb, flashcardDb } from '@/lib/supabase';

export async function POST() {
  try {
    console.log('Bắt đầu import IELTS Liz Vocabulary...');

    // Tạo các lessons theo chủ đề IELTS Liz
    const ieltsLizLessons = [
      {
        title: 'IELTS Liz - Education & Knowledge',
        description: 'Từ vựng giáo dục và kiến thức theo IELTS Liz',
        category: 'IELTS Liz'
      },
      {
        title: 'IELTS Liz - Technology & Media',
        description: 'Từ vựng công nghệ và truyền thông theo IELTS Liz',
        category: 'IELTS Liz'
      },
      {
        title: 'IELTS Liz - Environment & Nature',
        description: 'Từ vựng môi trường và thiên nhiên theo IELTS Liz',
        category: 'IELTS Liz'
      },
      {
        title: 'IELTS Liz - Health & Lifestyle',
        description: 'Từ vựng sức khỏe và lối sống theo IELTS Liz',
        category: 'IELTS Liz'
      },
      {
        title: 'IELTS Liz - Crime & Society',
        description: 'Từ vựng tội phạm và xã hội theo IELTS Liz',
        category: 'IELTS Liz'
      },
      {
        title: 'IELTS Liz - Work & Business',
        description: 'Từ vựng công việc và kinh doanh theo IELTS Liz',
        category: 'IELTS Liz'
      }
    ];

    // IELTS Liz vocabulary - 360 từ được chọn lọc theo chủ đề
    const ieltsLizVocabulary: Record<string, Array<{english: string; vietnamese: string; ipa: string}>> = {
      'IELTS Liz - Education & Knowledge': [
        // Education vocabulary - 60 từ
        { english: 'academic', vietnamese: 'học thuật', ipa: '/ˌækəˈdemɪk/' },
        { english: 'acquire', vietnamese: 'có được, học được', ipa: '/əˈkwaɪər/' },
        { english: 'curriculum', vietnamese: 'chương trình học', ipa: '/kəˈrɪkjələm/' },
        { english: 'discipline', vietnamese: 'kỷ luật, ngành học', ipa: '/ˈdɪsəplɪn/' },
        { english: 'elementary', vietnamese: 'cơ bản, tiểu học', ipa: '/ˌeləˈmentri/' },
        { english: 'faculty', vietnamese: 'khoa (đại học)', ipa: '/ˈfækəlti/' },
        { english: 'graduate', vietnamese: 'tốt nghiệp', ipa: '/ˈɡrædʒuət/' },
        { english: 'literacy', vietnamese: 'khả năng đọc viết', ipa: '/ˈlɪtərəsi/' },
        { english: 'methodology', vietnamese: 'phương pháp luận', ipa: '/ˌmeθəˈdɑːlədʒi/' },
        { english: 'pedagogy', vietnamese: 'sư phạm học', ipa: '/ˈpedəɡɑːdʒi/' },
        { english: 'qualification', vietnamese: 'bằng cấp', ipa: '/ˌkwɑːlɪfɪˈkeɪʃn/' },
        { english: 'scholarship', vietnamese: 'học bổng', ipa: '/ˈskɑːlərʃɪp/' },
        { english: 'tutorial', vietnamese: 'hướng dẫn', ipa: '/tuˈtɔːriəl/' },
        { english: 'undergraduate', vietnamese: 'sinh viên đại học', ipa: '/ˌʌndərˈɡrædʒuət/' },
        { english: 'assessment', vietnamese: 'đánh giá', ipa: '/əˈsesmənt/' },
        { english: 'certificate', vietnamese: 'chứng chỉ', ipa: '/sərˈtɪfɪkət/' },
        { english: 'diploma', vietnamese: 'bằng tốt nghiệp', ipa: '/dɪˈploʊmə/' },
        { english: 'enrollment', vietnamese: 'đăng ký học', ipa: '/ɪnˈroʊlmənt/' },
        { english: 'expertise', vietnamese: 'chuyên môn', ipa: '/ˌekspərˈtiːz/' },
        { english: 'fluency', vietnamese: 'sự trôi chảy', ipa: '/ˈfluːənsi/' },
        { english: 'intellectual', vietnamese: 'trí thức', ipa: '/ˌɪntəˈlektʃuəl/' },
        { english: 'knowledge', vietnamese: 'kiến thức', ipa: '/ˈnɑːlɪdʒ/' },
        { english: 'lecture', vietnamese: 'bài giảng', ipa: '/ˈlektʃər/' },
        { english: 'memorize', vietnamese: 'ghi nhớ', ipa: '/ˈmeməraɪz/' },
        { english: 'practical', vietnamese: 'thực tế', ipa: '/ˈpræktɪkl/' },
        { english: 'research', vietnamese: 'nghiên cứu', ipa: '/rɪˈsɜːrtʃ/' },
        { english: 'seminar', vietnamese: 'hội thảo', ipa: '/ˈsemɪnɑːr/' },
        { english: 'tuition', vietnamese: 'học phí', ipa: '/tuˈɪʃn/' },
        { english: 'vocational', vietnamese: 'nghề nghiệp', ipa: '/voʊˈkeɪʃənl/' },
        { english: 'workshop', vietnamese: 'hội thảo thực hành', ipa: '/ˈwɜːrkʃɑːp/' },
        { english: 'comprehension', vietnamese: 'sự hiểu biết', ipa: '/ˌkɑːmprɪˈhenʃn/' },
        { english: 'concentration', vietnamese: 'sự tập trung', ipa: '/ˌkɑːnsnˈtreɪʃn/' },
        { english: 'creativity', vietnamese: 'sự sáng tạo', ipa: '/ˌkriːeɪˈtɪvəti/' },
        { english: 'dedication', vietnamese: 'sự tận tụy', ipa: '/ˌdedɪˈkeɪʃn/' },
        { english: 'examination', vietnamese: 'kỳ thi', ipa: '/ɪɡˌzæməˈneɪʃn/' },
        { english: 'foundation', vietnamese: 'nền tảng', ipa: '/faʊnˈdeɪʃn/' },
        { english: 'guidance', vietnamese: 'sự hướng dẫn', ipa: '/ˈɡaɪdns/' },
        { english: 'homework', vietnamese: 'bài tập về nhà', ipa: '/ˈhoʊmwɜːrk/' },
        { english: 'institution', vietnamese: 'cơ sở giáo dục', ipa: '/ˌɪnstɪˈtuːʃn/' },
        { english: 'learning', vietnamese: 'việc học', ipa: '/ˈlɜːrnɪŋ/' },
        { english: 'motivation', vietnamese: 'động lực', ipa: '/ˌmoʊtɪˈveɪʃn/' },
        { english: 'notebook', vietnamese: 'sổ ghi chép', ipa: '/ˈnoʊtbʊk/' },
        { english: 'assignment', vietnamese: 'bài tập', ipa: '/əˈsaɪnmənt/' },
        { english: 'bachelor', vietnamese: 'cử nhân', ipa: '/ˈbætʃələr/' },
        { english: 'classroom', vietnamese: 'lớp học', ipa: '/ˈklæsruːm/' },
        { english: 'discussion', vietnamese: 'thảo luận', ipa: '/dɪˈskʌʃn/' },
        { english: 'education', vietnamese: 'giáo dục', ipa: '/ˌedʒuˈkeɪʃn/' },
        { english: 'feedback', vietnamese: 'phản hồi', ipa: '/ˈfiːdbæk/' },
        { english: 'handwriting', vietnamese: 'chữ viết tay', ipa: '/ˈhændˌraɪtɪŋ/' },
        { english: 'instructor', vietnamese: 'giảng viên', ipa: '/ɪnˈstrʌktər/' },
        { english: 'laboratory', vietnamese: 'phòng thí nghiệm', ipa: '/ˈlæbrətɔːri/' },
        { english: 'master', vietnamese: 'thạc sĩ', ipa: '/ˈmæstər/' },
        { english: 'nursery', vietnamese: 'nhà trẻ', ipa: '/ˈnɜːrsəri/' },
        { english: 'objective', vietnamese: 'mục tiêu', ipa: '/əbˈdʒektɪv/' },
        { english: 'professor', vietnamese: 'giáo sư', ipa: '/prəˈfesər/' },
        { english: 'revision', vietnamese: 'ôn tập', ipa: '/rɪˈvɪʒn/' },
        { english: 'student', vietnamese: 'học sinh, sinh viên', ipa: '/ˈstuːdnt/' },
        { english: 'textbook', vietnamese: 'sách giáo khoa', ipa: '/ˈtekstbʊk/' },
        { english: 'university', vietnamese: 'đại học', ipa: '/ˌjuːnɪˈvɜːrsəti/' },
        { english: 'vocabulary', vietnamese: 'từ vựng', ipa: '/voʊˈkæbjələri/' },
        { english: 'wisdom', vietnamese: 'sự khôn ngoan', ipa: '/ˈwɪzdəm/' }
      ],
      'IELTS Liz - Technology & Media': [
        // Technology & Media vocabulary - 60 từ
        { english: 'algorithm', vietnamese: 'thuật toán', ipa: '/ˈælɡərɪðəm/' },
        { english: 'application', vietnamese: 'ứng dụng', ipa: '/ˌæplɪˈkeɪʃn/' },
        { english: 'bandwidth', vietnamese: 'băng thông', ipa: '/ˈbændwɪdθ/' },
        { english: 'cyber', vietnamese: 'mạng, ảo', ipa: '/ˈsaɪbər/' },
        { english: 'database', vietnamese: 'cơ sở dữ liệu', ipa: '/ˈdeɪtəbeɪs/' },
        { english: 'electronic', vietnamese: 'điện tử', ipa: '/ɪˌlekˈtrɑːnɪk/' },
        { english: 'fiber', vietnamese: 'cáp quang', ipa: '/ˈfaɪbər/' },
        { english: 'gadget', vietnamese: 'thiết bị', ipa: '/ˈɡædʒət/' },
        { english: 'hardware', vietnamese: 'phần cứng', ipa: '/ˈhɑːrdwer/' },
        { english: 'interface', vietnamese: 'giao diện', ipa: '/ˈɪntərfeɪs/' },
        { english: 'keyboard', vietnamese: 'bàn phím', ipa: '/ˈkiːbɔːrd/' },
        { english: 'laptop', vietnamese: 'máy tính xách tay', ipa: '/ˈlæptɑːp/' },
        { english: 'multimedia', vietnamese: 'đa phương tiện', ipa: '/ˌmʌltiˈmiːdiə/' },
        { english: 'network', vietnamese: 'mạng lưới', ipa: '/ˈnetwɜːrk/' },
        { english: 'online', vietnamese: 'trực tuyến', ipa: '/ˌɑːnˈlaɪn/' },
        { english: 'programming', vietnamese: 'lập trình', ipa: '/ˈproʊɡræmɪŋ/' },
        { english: 'robot', vietnamese: 'người máy', ipa: '/ˈroʊbɑːt/' },
        { english: 'software', vietnamese: 'phần mềm', ipa: '/ˈsɔːftwer/' },
        { english: 'technology', vietnamese: 'công nghệ', ipa: '/tekˈnɑːlədʒi/' },
        { english: 'upgrade', vietnamese: 'nâng cấp', ipa: '/ˈʌpɡreɪd/' },
        { english: 'virtual', vietnamese: 'ảo', ipa: '/ˈvɜːrtʃuəl/' },
        { english: 'wireless', vietnamese: 'không dây', ipa: '/ˈwaɪərləs/' },
        { english: 'artificial', vietnamese: 'nhân tạo', ipa: '/ˌɑːrtɪˈfɪʃl/' },
        { english: 'broadcast', vietnamese: 'phát sóng', ipa: '/ˈbrɔːdkæst/' },
        { english: 'communication', vietnamese: 'giao tiếp', ipa: '/kəˌmjuːnɪˈkeɪʃn/' },
        { english: 'digital', vietnamese: 'kỹ thuật số', ipa: '/ˈdɪdʒɪtl/' },
        { english: 'entertainment', vietnamese: 'giải trí', ipa: '/ˌentərˈteɪnmənt/' },
        { english: 'facebook', vietnamese: 'Facebook', ipa: '/ˈfeɪsbʊk/' },
        { english: 'google', vietnamese: 'Google', ipa: '/ˈɡuːɡl/' },
        { english: 'internet', vietnamese: 'mạng internet', ipa: '/ˈɪntərnet/' },
        { english: 'journalism', vietnamese: 'báo chí', ipa: '/ˈdʒɜːrnəlɪzəm/' },
        { english: 'keyboard', vietnamese: 'bàn phím', ipa: '/ˈkiːbɔːrd/' },
        { english: 'mobile', vietnamese: 'di động', ipa: '/ˈmoʊbl/' },
        { english: 'notification', vietnamese: 'thông báo', ipa: '/ˌnoʊtɪfɪˈkeɪʃn/' },
        { english: 'operating', vietnamese: 'vận hành', ipa: '/ˈɑːpəreɪtɪŋ/' },
        { english: 'platform', vietnamese: 'nền tảng', ipa: '/ˈplætfɔːrm/' },
        { english: 'revolution', vietnamese: 'cách mạng', ipa: '/ˌrevəˈluːʃn/' },
        { english: 'smartphone', vietnamese: 'điện thoại thông minh', ipa: '/ˈsmɑːrtfoʊn/' },
        { english: 'television', vietnamese: 'truyền hình', ipa: '/ˈtelɪvɪʒn/' },
        { english: 'update', vietnamese: 'cập nhật', ipa: '/ˌʌpˈdeɪt/' },
        { english: 'video', vietnamese: 'video', ipa: '/ˈvɪdioʊ/' },
        { english: 'website', vietnamese: 'trang web', ipa: '/ˈwebsaɪt/' },
        { english: 'automation', vietnamese: 'tự động hóa', ipa: '/ˌɔːtəˈmeɪʃn/' },
        { english: 'backup', vietnamese: 'sao lưu', ipa: '/ˈbækʌp/' },
        { english: 'computing', vietnamese: 'điện toán', ipa: '/kəmˈpjuːtɪŋ/' },
        { english: 'download', vietnamese: 'tải xuống', ipa: '/ˈdaʊnloʊd/' },
        { english: 'email', vietnamese: 'thư điện tử', ipa: '/ˈiːmeɪl/' },
        { english: 'facebook', vietnamese: 'Facebook', ipa: '/ˈfeɪsbʊk/' },
        { english: 'gaming', vietnamese: 'chơi game', ipa: '/ˈɡeɪmɪŋ/' },
        { english: 'hacking', vietnamese: 'hack, xâm nhập', ipa: '/ˈhækɪŋ/' },
        { english: 'innovation', vietnamese: 'đổi mới', ipa: '/ˌɪnəˈveɪʃn/' },
        { english: 'microphone', vietnamese: 'micro', ipa: '/ˈmaɪkrəfoʊn/' },
        { english: 'privacy', vietnamese: 'quyền riêng tư', ipa: '/ˈpraɪvəsi/' },
        { english: 'security', vietnamese: 'bảo mật', ipa: '/sɪˈkjʊrəti/' },
        { english: 'streaming', vietnamese: 'phát trực tuyến', ipa: '/ˈstriːmɪŋ/' },
        { english: 'tablet', vietnamese: 'máy tính bảng', ipa: '/ˈtæblət/' },
        { english: 'username', vietnamese: 'tên người dùng', ipa: '/ˈjuːzərneɪm/' },
        { english: 'virus', vietnamese: 'vi-rút', ipa: '/ˈvaɪrəs/' },
        { english: 'wifi', vietnamese: 'Wi-Fi', ipa: '/ˈwaɪfaɪ/' },
        { english: 'youtube', vietnamese: 'YouTube', ipa: '/ˈjuːtuːb/' }
      ],
      'IELTS Liz - Environment & Nature': [
        // Environment & Nature vocabulary - 60 từ
        { english: 'atmosphere', vietnamese: 'khí quyển', ipa: '/ˈætməsfɪr/' },
        { english: 'biodiversity', vietnamese: 'đa dạng sinh học', ipa: '/ˌbaɪoʊdaɪˈvɜːrsəti/' },
        { english: 'climate', vietnamese: 'khí hậu', ipa: '/ˈklaɪmət/' },
        { english: 'deforestation', vietnamese: 'phá rừng', ipa: '/diˌfɔːrɪˈsteɪʃn/' },
        { english: 'ecosystem', vietnamese: 'hệ sinh thái', ipa: '/ˈiːkoʊsɪstəm/' },
        { english: 'fossil', vietnamese: 'hóa thạch', ipa: '/ˈfɑːsl/' },
        { english: 'greenhouse', vietnamese: 'nhà kính', ipa: '/ˈɡriːnhaʊs/' },
        { english: 'habitat', vietnamese: 'môi trường sống', ipa: '/ˈhæbɪtæt/' },
        { english: 'irrigation', vietnamese: 'tưới tiêu', ipa: '/ˌɪrɪˈɡeɪʃn/' },
        { english: 'landscape', vietnamese: 'cảnh quan', ipa: '/ˈlændskeɪp/' },
        { english: 'marine', vietnamese: 'biển, hàng hải', ipa: '/məˈriːn/' },
        { english: 'natural', vietnamese: 'tự nhiên', ipa: '/ˈnætʃrəl/' },
        { english: 'organic', vietnamese: 'hữu cơ', ipa: '/ɔːrˈɡænɪk/' },
        { english: 'pollution', vietnamese: 'ô nhiễm', ipa: '/pəˈluːʃn/' },
        { english: 'recycling', vietnamese: 'tái chế', ipa: '/riˈsaɪklɪŋ/' },
        { english: 'sustainability', vietnamese: 'tính bền vững', ipa: '/səˌsteɪnəˈbɪləti/' },
        { english: 'toxic', vietnamese: 'độc hại', ipa: '/ˈtɑːksɪk/' },
        { english: 'urban', vietnamese: 'đô thị', ipa: '/ˈɜːrbən/' },
        { english: 'vegetation', vietnamese: 'thảm thực vật', ipa: '/ˌvedʒəˈteɪʃn/' },
        { english: 'wildlife', vietnamese: 'động vật hoang dã', ipa: '/ˈwaɪldlaɪf/' },
        { english: 'conservation', vietnamese: 'bảo tồn', ipa: '/ˌkɑːnsərˈveɪʃn/' },
        { english: 'contamination', vietnamese: 'nhiễm bẩn', ipa: '/kənˌtæməˈneɪʃn/' },
        { english: 'cultivation', vietnamese: 'canh tác', ipa: '/ˌkʌltəˈveɪʃn/' },
        { english: 'emission', vietnamese: 'khí thải', ipa: '/ɪˈmɪʃn/' },
        { english: 'extinction', vietnamese: 'tuyệt chủng', ipa: '/ɪkˈstɪŋkʃn/' },
        { english: 'fertilizer', vietnamese: 'phân bón', ipa: '/ˈfɜːrtəlaɪzər/' },
        { english: 'global', vietnamese: 'toàn cầu', ipa: '/ˈɡloʊbl/' },
        { english: 'hurricane', vietnamese: 'bão', ipa: '/ˈhɜːrəkən/' },
        { english: 'industrial', vietnamese: 'công nghiệp', ipa: '/ɪnˈdʌstriəl/' },
        { english: 'jungle', vietnamese: 'rừng rậm', ipa: '/ˈdʒʌŋɡl/' },
        { english: 'landfill', vietnamese: 'bãi chôn lấp', ipa: '/ˈlændfɪl/' },
        { english: 'mineral', vietnamese: 'khoáng chất', ipa: '/ˈmɪnərəl/' },
        { english: 'nuclear', vietnamese: 'hạt nhân', ipa: '/ˈnuːkliər/' },
        { english: 'ozone', vietnamese: 'tầng ozon', ipa: '/ˈoʊzoʊn/' },
        { english: 'pesticide', vietnamese: 'thuốc trừ sâu', ipa: '/ˈpestɪsaɪd/' },
        { english: 'renewable', vietnamese: 'tái tạo', ipa: '/rɪˈnuːəbl/' },
        { english: 'solar', vietnamese: 'năng lượng mặt trời', ipa: '/ˈsoʊlər/' },
        { english: 'temperature', vietnamese: 'nhiệt độ', ipa: '/ˈtemprətʃər/' },
        { english: 'underground', vietnamese: 'dưới lòng đất', ipa: '/ˌʌndərˈɡraʊnd/' },
        { english: 'volcano', vietnamese: 'núi lửa', ipa: '/vɑːlˈkeɪnoʊ/' },
        { english: 'waste', vietnamese: 'chất thải', ipa: '/weɪst/' },
        { english: 'agriculture', vietnamese: 'nông nghiệp', ipa: '/ˈæɡrɪkʌltʃər/' },
        { english: 'biodegradable', vietnamese: 'phân hủy sinh học', ipa: '/ˌbaɪoʊdɪˈɡreɪdəbl/' },
        { english: 'carbon', vietnamese: 'carbon', ipa: '/ˈkɑːrbən/' },
        { english: 'drought', vietnamese: 'hạn hán', ipa: '/draʊt/' },
        { english: 'environment', vietnamese: 'môi trường', ipa: '/ɪnˈvaɪrənmənt/' },
        { english: 'flooding', vietnamese: 'lũ lụt', ipa: '/ˈflʌdɪŋ/' },
        { english: 'genetic', vietnamese: 'di truyền', ipa: '/dʒəˈnetɪk/' },
        { english: 'hunting', vietnamese: 'săn bắn', ipa: '/ˈhʌntɪŋ/' },
        { english: 'ice', vietnamese: 'băng', ipa: '/aɪs/' },
        { english: 'jungle', vietnamese: 'rừng rậm', ipa: '/ˈdʒʌŋɡl/' },
        { english: 'kelp', vietnamese: 'tảo bẹ', ipa: '/kelp/' },
        { english: 'logging', vietnamese: 'khai thác gỗ', ipa: '/ˈlɔːɡɪŋ/' },
        { english: 'mammal', vietnamese: 'động vật có vú', ipa: '/ˈmæml/' },
        { english: 'nature', vietnamese: 'thiên nhiên', ipa: '/ˈneɪtʃər/' },
        { english: 'ocean', vietnamese: 'đại dương', ipa: '/ˈoʊʃn/' },
        { english: 'plantation', vietnamese: 'đồn điền', ipa: '/plænˈteɪʃn/' },
        { english: 'rainforest', vietnamese: 'rừng mưa nhiệt đới', ipa: '/ˈreɪnfɔːrəst/' },
        { english: 'species', vietnamese: 'loài', ipa: '/ˈspiːʃiːz/' },
        { english: 'timber', vietnamese: 'gỗ xây dựng', ipa: '/ˈtɪmbər/' },
        { english: 'wetland', vietnamese: 'đất ngập nước', ipa: '/ˈwetlənd/' }
      ],
      'IELTS Liz - Health & Lifestyle': [
        // Health & Lifestyle vocabulary - 60 từ
        { english: 'addiction', vietnamese: 'nghiện', ipa: '/əˈdɪkʃn/' },
        { english: 'balanced', vietnamese: 'cân bằng', ipa: '/ˈbælənst/' },
        { english: 'calories', vietnamese: 'calo', ipa: '/ˈkæləriz/' },
        { english: 'diet', vietnamese: 'chế độ ăn', ipa: '/ˈdaɪət/' },
        { english: 'exercise', vietnamese: 'tập thể dục', ipa: '/ˈeksərsaɪz/' },
        { english: 'fitness', vietnamese: 'thể lực', ipa: '/ˈfɪtnəs/' },
        { english: 'hygiene', vietnamese: 'vệ sinh', ipa: '/ˈhaɪdʒiːn/' },
        { english: 'illness', vietnamese: 'bệnh tật', ipa: '/ˈɪlnəs/' },
        { english: 'junk', vietnamese: 'đồ ăn vặt', ipa: '/dʒʌŋk/' },
        { english: 'lifestyle', vietnamese: 'lối sống', ipa: '/ˈlaɪfstaɪl/' },
        { english: 'meditation', vietnamese: 'thiền định', ipa: '/ˌmedɪˈteɪʃn/' },
        { english: 'nutrition', vietnamese: 'dinh dưỡng', ipa: '/nuˈtrɪʃn/' },
        { english: 'obesity', vietnamese: 'béo phì', ipa: '/oʊˈbiːsəti/' },
        { english: 'prevention', vietnamese: 'phòng ngừa', ipa: '/prɪˈvenʃn/' },
        { english: 'quarantine', vietnamese: 'cách ly', ipa: '/ˈkwɔːrəntiːn/' },
        { english: 'relaxation', vietnamese: 'thư giãn', ipa: '/ˌriːlækˈseɪʃn/' },
        { english: 'smoking', vietnamese: 'hút thuốc', ipa: '/ˈsmoʊkɪŋ/' },
        { english: 'therapy', vietnamese: 'liệu pháp', ipa: '/ˈθerəpi/' },
        { english: 'vaccination', vietnamese: 'tiêm chủng', ipa: '/ˌvæksəˈneɪʃn/' },
        { english: 'wellness', vietnamese: 'sức khỏe tổng thể', ipa: '/ˈwelnəs/' },
        { english: 'alcohol', vietnamese: 'rượu', ipa: '/ˈælkəhɔːl/' },
        { english: 'bacteria', vietnamese: 'vi khuẩn', ipa: '/bækˈtɪriə/' },
        { english: 'checkup', vietnamese: 'khám sức khỏe', ipa: '/ˈtʃekʌp/' },
        { english: 'diabetes', vietnamese: 'tiểu đường', ipa: '/ˌdaɪəˈbiːtiːz/' },
        { english: 'epidemic', vietnamese: 'dịch bệnh', ipa: '/ˌepɪˈdemɪk/' },
        { english: 'fever', vietnamese: 'sốt', ipa: '/ˈfiːvər/' },
        { english: 'gymnasium', vietnamese: 'phòng tập thể dục', ipa: '/dʒɪmˈneɪziəm/' },
        { english: 'headache', vietnamese: 'đau đầu', ipa: '/ˈhedeɪk/' },
        { english: 'immune', vietnamese: 'miễn dịch', ipa: '/ɪˈmjuːn/' },
        { english: 'jogging', vietnamese: 'chạy bộ', ipa: '/ˈdʒɑːɡɪŋ/' },
        { english: 'kidney', vietnamese: 'thận', ipa: '/ˈkɪdni/' },
        { english: 'liver', vietnamese: 'gan', ipa: '/ˈlɪvər/' },
        { english: 'medicine', vietnamese: 'thuốc', ipa: '/ˈmedsn/' },
        { english: 'nurse', vietnamese: 'y tá', ipa: '/nɜːrs/' },
        { english: 'operation', vietnamese: 'phẫu thuật', ipa: '/ˌɑːpəˈreɪʃn/' },
        { english: 'pharmacy', vietnamese: 'hiệu thuốc', ipa: '/ˈfɑːrməsi/' },
        { english: 'recipe', vietnamese: 'công thức', ipa: '/ˈresəpi/' },
        { english: 'surgery', vietnamese: 'phẫu thuật', ipa: '/ˈsɜːrdʒəri/' },
        { english: 'treatment', vietnamese: 'điều trị', ipa: '/ˈtriːtmənt/' },
        { english: 'vitamins', vietnamese: 'vitamin', ipa: '/ˈvaɪtəmɪnz/' },
        { english: 'walking', vietnamese: 'đi bộ', ipa: '/ˈwɔːkɪŋ/' },
        { english: 'anxiety', vietnamese: 'lo âu', ipa: '/æŋˈzaɪəti/' },
        { english: 'blood', vietnamese: 'máu', ipa: '/blʌd/' },
        { english: 'cancer', vietnamese: 'ung thư', ipa: '/ˈkænsər/' },
        { english: 'depression', vietnamese: 'trầm cảm', ipa: '/dɪˈpreʃn/' },
        { english: 'emergency', vietnamese: 'cấp cứu', ipa: '/ɪˈmɜːrdʒənsi/' },
        { english: 'flu', vietnamese: 'cúm', ipa: '/fluː/' },
        { english: 'germs', vietnamese: 'vi trùng', ipa: '/dʒɜːrmz/' },
        { english: 'hospital', vietnamese: 'bệnh viện', ipa: '/ˈhɑːspɪtl/' },
        { english: 'infection', vietnamese: 'nhiễm trùng', ipa: '/ɪnˈfekʃn/' },
        { english: 'joint', vietnamese: 'khớp', ipa: '/dʒɔɪnt/' },
        { english: 'lungs', vietnamese: 'phổi', ipa: '/lʌŋz/' },
        { english: 'muscle', vietnamese: 'cơ bắp', ipa: '/ˈmʌsl/' },
        { english: 'nutrient', vietnamese: 'chất dinh dưỡng', ipa: '/ˈnuːtriənt/' },
        { english: 'organic', vietnamese: 'hữu cơ', ipa: '/ɔːrˈɡænɪk/' },
        { english: 'patient', vietnamese: 'bệnh nhân', ipa: '/ˈpeɪʃnt/' },
        { english: 'recovery', vietnamese: 'hồi phục', ipa: '/rɪˈkʌvəri/' },
        { english: 'stress', vietnamese: 'căng thẳng', ipa: '/stres/' },
        { english: 'toxic', vietnamese: 'độc hại', ipa: '/ˈtɑːksɪk/' },
        { english: 'virus', vietnamese: 'vi-rút', ipa: '/ˈvaɪrəs/' },
        { english: 'yoga', vietnamese: 'yoga', ipa: '/ˈjoʊɡə/' }
      ],
      'IELTS Liz - Crime & Society': [
        // Crime & Society vocabulary - 60 từ
        { english: 'arrest', vietnamese: 'bắt giữ', ipa: '/əˈrest/' },
        { english: 'burglary', vietnamese: 'trộm cắp', ipa: '/ˈbɜːrɡləri/' },
        { english: 'criminal', vietnamese: 'tội phạm', ipa: '/ˈkrɪmɪnl/' },
        { english: 'detective', vietnamese: 'thám tử', ipa: '/dɪˈtektɪv/' },
        { english: 'evidence', vietnamese: 'bằng chứng', ipa: '/ˈevɪdəns/' },
        { english: 'fingerprint', vietnamese: 'dấu vân tay', ipa: '/ˈfɪŋɡərprɪnt/' },
        { english: 'guilty', vietnamese: 'có tội', ipa: '/ˈɡɪlti/' },
        { english: 'homicide', vietnamese: 'giết người', ipa: '/ˈhɑːməsaɪd/' },
        { english: 'investigation', vietnamese: 'điều tra', ipa: '/ɪnˌvestɪˈɡeɪʃn/' },
        { english: 'justice', vietnamese: 'công lý', ipa: '/ˈdʒʌstɪs/' },
        { english: 'kidnapping', vietnamese: 'bắt cóc', ipa: '/ˈkɪdnæpɪŋ/' },
        { english: 'law', vietnamese: 'luật pháp', ipa: '/lɔː/' },
        { english: 'murder', vietnamese: 'giết người', ipa: '/ˈmɜːrdər/' },
        { english: 'offender', vietnamese: 'người phạm tội', ipa: '/əˈfendər/' },
        { english: 'prison', vietnamese: 'nhà tù', ipa: '/ˈprɪzn/' },
        { english: 'robbery', vietnamese: 'cướp', ipa: '/ˈrɑːbəri/' },
        { english: 'sentence', vietnamese: 'bản án', ipa: '/ˈsentəns/' },
        { english: 'theft', vietnamese: 'trộm cắp', ipa: '/θeft/' },
        { english: 'vandalism', vietnamese: 'phá hoại', ipa: '/ˈvændəlɪzəm/' },
        { english: 'witness', vietnamese: 'nhân chứng', ipa: '/ˈwɪtnəs/' },
        { english: 'assault', vietnamese: 'tấn công', ipa: '/əˈsɔːlt/' },
        { english: 'bribery', vietnamese: 'hối lộ', ipa: '/ˈbraɪbəri/' },
        { english: 'corruption', vietnamese: 'tham nhũng', ipa: '/kəˈrʌpʃn/' },
        { english: 'drugs', vietnamese: 'ma túy', ipa: '/drʌɡz/' },
        { english: 'embezzlement', vietnamese: 'biển thủ', ipa: '/ɪmˈbezlmənt/' },
        { english: 'fraud', vietnamese: 'gian lận', ipa: '/frɔːd/' },
        { english: 'gang', vietnamese: 'băng nhóm', ipa: '/ɡæŋ/' },
        { english: 'harassment', vietnamese: 'quấy rối', ipa: '/həˈræsmənt/' },
        { english: 'illegal', vietnamese: 'bất hợp pháp', ipa: '/ɪˈliːɡl/' },
        { english: 'jail', vietnamese: 'nhà tù', ipa: '/dʒeɪl/' },
        { english: 'knife', vietnamese: 'dao', ipa: '/naɪf/' },
        { english: 'lawsuit', vietnamese: 'vụ kiện', ipa: '/ˈlɔːsuːt/' },
        { english: 'misconduct', vietnamese: 'hành vi sai trái', ipa: '/ˌmɪsˈkɑːndʌkt/' },
        { english: 'narcotics', vietnamese: 'ma túy', ipa: '/nɑːrˈkɑːtɪks/' },
        { english: 'offense', vietnamese: 'tội lỗi', ipa: '/əˈfens/' },
        { english: 'punishment', vietnamese: 'hình phạt', ipa: '/ˈpʌnɪʃmənt/' },
        { english: 'rehabilitation', vietnamese: 'cải tạo', ipa: '/ˌriːəˌbɪləˈteɪʃn/' },
        { english: 'security', vietnamese: 'an ninh', ipa: '/sɪˈkjʊrəti/' },
        { english: 'trial', vietnamese: 'phiên tòa', ipa: '/ˈtraɪəl/' },
        { english: 'violence', vietnamese: 'bạo lực', ipa: '/ˈvaɪələns/' },
        { english: 'weapon', vietnamese: 'vũ khí', ipa: '/ˈwepən/' },
        { english: 'adolescent', vietnamese: 'thanh thiếu niên', ipa: '/ˌædəˈlesnt/' },
        { english: 'behavior', vietnamese: 'hành vi', ipa: '/bɪˈheɪvjər/' },
        { english: 'community', vietnamese: 'cộng đồng', ipa: '/kəˈmjuːnəti/' },
        { english: 'delinquent', vietnamese: 'phạm pháp', ipa: '/dɪˈlɪŋkwənt/' },
        { english: 'education', vietnamese: 'giáo dục', ipa: '/ˌedʒuˈkeɪʃn/' },
        { english: 'family', vietnamese: 'gia đình', ipa: '/ˈfæməli/' },
        { english: 'government', vietnamese: 'chính phủ', ipa: '/ˈɡʌvərnmənt/' },
        { english: 'homeless', vietnamese: 'vô gia cư', ipa: '/ˈhoʊmləs/' },
        { english: 'inequality', vietnamese: 'bất bình đẳng', ipa: '/ˌɪnɪˈkwɑːləti/' },
        { english: 'juvenile', vietnamese: 'vị thành niên', ipa: '/ˈdʒuːvənaɪl/' },
        { english: 'legislation', vietnamese: 'luật pháp', ipa: '/ˌledʒɪsˈleɪʃn/' },
        { english: 'morality', vietnamese: 'đạo đức', ipa: '/məˈræləti/' },
        { english: 'neighborhood', vietnamese: 'khu phố', ipa: '/ˈneɪbərˌhʊd/' },
        { english: 'order', vietnamese: 'trật tự', ipa: '/ˈɔːrdər/' },
        { english: 'poverty', vietnamese: 'nghèo đói', ipa: '/ˈpɑːvərti/' },
        { english: 'reform', vietnamese: 'cải cách', ipa: '/rɪˈfɔːrm/' },
        { english: 'society', vietnamese: 'xã hội', ipa: '/səˈsaɪəti/' },
        { english: 'tolerance', vietnamese: 'sự khoan dung', ipa: '/ˈtɑːlərəns/' },
        { english: 'urban', vietnamese: 'đô thị', ipa: '/ˈɜːrbən/' },
        { english: 'youth', vietnamese: 'thanh niên', ipa: '/juːθ/' }
      ],
      'IELTS Liz - Work & Business': [
        // Work & Business vocabulary - 60 từ
        { english: 'achievement', vietnamese: 'thành tựu', ipa: '/əˈtʃiːvmənt/' },
        { english: 'benefit', vietnamese: 'lợi ích', ipa: '/ˈbenəfɪt/' },
        { english: 'career', vietnamese: 'sự nghiệp', ipa: '/kəˈrɪr/' },
        { english: 'deadline', vietnamese: 'hạn chót', ipa: '/ˈdedlaɪn/' },
        { english: 'entrepreneur', vietnamese: 'doanh nhân', ipa: '/ˌɑːntrəprəˈnɜːr/' },
        { english: 'finance', vietnamese: 'tài chính', ipa: '/ˈfaɪnæns/' },
        { english: 'goal', vietnamese: 'mục tiêu', ipa: '/ɡoʊl/' },
        { english: 'hierarchy', vietnamese: 'hệ thống cấp bậc', ipa: '/ˈhaɪərɑːrki/' },
        { english: 'income', vietnamese: 'thu nhập', ipa: '/ˈɪnkʌm/' },
        { english: 'job', vietnamese: 'công việc', ipa: '/dʒɑːb/' },
        { english: 'knowledge', vietnamese: 'kiến thức', ipa: '/ˈnɑːlɪdʒ/' },
        { english: 'leadership', vietnamese: 'lãnh đạo', ipa: '/ˈliːdərʃɪp/' },
        { english: 'management', vietnamese: 'quản lý', ipa: '/ˈmænɪdʒmənt/' },
        { english: 'negotiation', vietnamese: 'đàm phán', ipa: '/nɪˌɡoʊʃiˈeɪʃn/' },
        { english: 'opportunity', vietnamese: 'cơ hội', ipa: '/ˌɑːpərˈtuːnəti/' },
        { english: 'performance', vietnamese: 'hiệu suất', ipa: '/pərˈfɔːrməns/' },
        { english: 'qualification', vietnamese: 'trình độ', ipa: '/ˌkwɑːlɪfɪˈkeɪʃn/' },
        { english: 'responsibility', vietnamese: 'trách nhiệm', ipa: '/rɪˌspɑːnsəˈbɪləti/' },
        { english: 'salary', vietnamese: 'lương', ipa: '/ˈsæləri/' },
        { english: 'teamwork', vietnamese: 'làm việc nhóm', ipa: '/ˈtiːmwɜːrk/' },
        { english: 'unemployment', vietnamese: 'thất nghiệp', ipa: '/ˌʌnɪmˈplɔɪmənt/' },
        { english: 'vacation', vietnamese: 'kỳ nghỉ', ipa: '/veɪˈkeɪʃn/' },
        { english: 'workplace', vietnamese: 'nơi làm việc', ipa: '/ˈwɜːrkpleɪs/' },
        { english: 'advertising', vietnamese: 'quảng cáo', ipa: '/ˈædvərtaɪzɪŋ/' },
        { english: 'budget', vietnamese: 'ngân sách', ipa: '/ˈbʌdʒɪt/' },
        { english: 'competition', vietnamese: 'cạnh tranh', ipa: '/ˌkɑːmpəˈtɪʃn/' },
        { english: 'customer', vietnamese: 'khách hàng', ipa: '/ˈkʌstəmər/' },
        { english: 'employee', vietnamese: 'nhân viên', ipa: '/ɪmˈplɔɪiː/' },
        { english: 'franchise', vietnamese: 'nhượng quyền', ipa: '/ˈfræntʃaɪz/' },
        { english: 'globalization', vietnamese: 'toàn cầu hóa', ipa: '/ˌɡloʊbələˈzeɪʃn/' },
        { english: 'headquarters', vietnamese: 'trụ sở chính', ipa: '/ˈhedkwɔːrtərz/' },
        { english: 'investment', vietnamese: 'đầu tư', ipa: '/ɪnˈvestmənt/' },
        { english: 'joint', vietnamese: 'liên doanh', ipa: '/dʒɔɪnt/' },
        { english: 'keynote', vietnamese: 'diễn văn chính', ipa: '/ˈkiːnoʊt/' },
        { english: 'logistics', vietnamese: 'hậu cần', ipa: '/ləˈdʒɪstɪks/' },
        { english: 'marketing', vietnamese: 'tiếp thị', ipa: '/ˈmɑːrkətɪŋ/' },
        { english: 'network', vietnamese: 'mạng lưới', ipa: '/ˈnetwɜːrk/' },
        { english: 'outsourcing', vietnamese: 'thuê ngoài', ipa: '/ˈaʊtsɔːrsɪŋ/' },
        { english: 'profit', vietnamese: 'lợi nhuận', ipa: '/ˈprɑːfɪt/' },
        { english: 'quality', vietnamese: 'chất lượng', ipa: '/ˈkwɑːləti/' },
        { english: 'revenue', vietnamese: 'doanh thu', ipa: '/ˈrevənuː/' },
        { english: 'stakeholder', vietnamese: 'bên liên quan', ipa: '/ˈsteɪkhoʊldər/' },
        { english: 'training', vietnamese: 'đào tạo', ipa: '/ˈtreɪnɪŋ/' },
        { english: 'union', vietnamese: 'công đoàn', ipa: '/ˈjuːnjən/' },
        { english: 'venture', vietnamese: 'dự án', ipa: '/ˈventʃər/' },
        { english: 'warehouse', vietnamese: 'kho', ipa: '/ˈwerhaʊs/' },
        { english: 'accounting', vietnamese: 'kế toán', ipa: '/əˈkaʊntɪŋ/' },
        { english: 'bankrupt', vietnamese: 'phá sản', ipa: '/ˈbæŋkrʌpt/' },
        { english: 'corporation', vietnamese: 'tập đoàn', ipa: '/ˌkɔːrpəˈreɪʃn/' },
        { english: 'delegate', vietnamese: 'ủy quyền', ipa: '/ˈdelɪɡət/' },
        { english: 'efficiency', vietnamese: 'hiệu quả', ipa: '/ɪˈfɪʃnsi/' },
        { english: 'factory', vietnamese: 'nhà máy', ipa: '/ˈfæktəri/' },
        { english: 'goods', vietnamese: 'hàng hóa', ipa: '/ɡʊdz/' },
        { english: 'human', vietnamese: 'nhân sự', ipa: '/ˈhjuːmən/' },
        { english: 'innovation', vietnamese: 'đổi mới', ipa: '/ˌɪnəˈveɪʃn/' },
        { english: 'manufacturing', vietnamese: 'sản xuất', ipa: '/ˌmænjəˈfæktʃərɪŋ/' },
        { english: 'overtime', vietnamese: 'làm thêm giờ', ipa: '/ˈoʊvərtaɪm/' },
        { english: 'productivity', vietnamese: 'năng suất', ipa: '/ˌproʊdʌkˈtɪvəti/' },
        { english: 'retirement', vietnamese: 'nghỉ hưu', ipa: '/rɪˈtaɪərmənt/' },
        { english: 'strategy', vietnamese: 'chiến lược', ipa: '/ˈstrætədʒi/' },
        { english: 'supervisor', vietnamese: 'giám sát viên', ipa: '/ˈsuːpərvaɪzər/' }
      ]
    };

    const results = [];

    // Import từng lesson
    for (const lessonData of ieltsLizLessons) {
      console.log(`Tạo lesson: ${lessonData.title}`);
      
      const lesson = await lessonDb.create({
        name: lessonData.title,
        description: lessonData.description,
        color: '#f59e0b'
      });

      if (lesson?.id) {
        const vocabularyList = ieltsLizVocabulary[lessonData.title] || [];
        console.log(`Import ${vocabularyList.length} từ vựng cho lesson: ${lessonData.title}`);

        // Import flashcards cho lesson này
        for (const vocab of vocabularyList) {
          try {
            await flashcardDb.create({
              english: vocab.english,
              vietnamese: vocab.vietnamese,
              ipa: vocab.ipa,
              category: 'IELTS',
              difficulty: 4,
              lesson_id: lesson.id
            });
          } catch (error) {
            console.error(`Lỗi khi tạo flashcard cho từ "${vocab.english}":`, error);
          }
        }

        results.push({
          lesson: lessonData.title,
          flashcards_count: vocabularyList.length
        });
      }
    }

    console.log('Hoàn thành import IELTS Liz Vocabulary!');
    
    return NextResponse.json({
      success: true,
      message: 'Import IELTS Liz Vocabulary thành công!',
      results: results,
      total_lessons: results.length,
      total_flashcards: results.reduce((sum, r) => sum + r.flashcards_count, 0)
    });

  } catch (error) {
    console.error('Lỗi khi import IELTS Liz Vocabulary:', error);
    return NextResponse.json({
      success: false,
      error: 'Có lỗi xảy ra khi import IELTS Liz Vocabulary',
      details: error instanceof Error ? error.message : 'Unknown error'
    }, { status: 500 });
  }
}
